var d = {
    "Notification Id": "1077",
    "Notification Name": "Accept Intake Email - Fees due",
    "Instance Id": "128903",
    "Instance History Id": "260667",
    "Action": "AcceptIntake",
    "Action Date": "11/29/2016 3:34:31 PM",
    "Previous Status": "WaitingForIntake",
    "Current Status": "FeesPending",
    "AREA": "12",
    "BUILDING_NUMBER": "Natus itaque quis eligendi rerum praesentium",
    "CONTRACTOR_ZIP": "52935",
    "LOT": "Quasi dolores officiis ipsa nihil molestias culpa perferendis esse ullamco sint assumenda possimus",
    "PARCEL_NO": "123",
    "PERMIT_ICN": "426",
    "PERMIT_TYPE": "Commercial Building Permit",
    "SAGES_ICN": "BLD-16-000160"
};

var d2 = {
    "Notification Id": 1077,
    "Notification Name": "Accept Intake Email - Fees due",
    "Instance Id": 128799,
    "Instance History Id": 261252,
    "Action": "AcceptIntake",
    "Action Date": "1/4/2017 3:10:10 PM",
    "Previous Status": "WaitingForIntake",
    "Current Status": "FeesPending",
    "APPLICATION_DATE": "10/28/2016",
    "BUILDING_NUMBER": "Esse quidem assumenda et amet et nostrum incidunt eum magnam quia dolore non odio incididunt omnis adipisci velit",
    "CONTACT": "Colt Norman",
    "CONTACT_ADDRESS": "At dolorem ut inventore id mollitia id minus eveniet molestiae quia porro quod",
    "CONTACT_CITY": "Sequi molestias illum, eum.",
    "CONTACT_EMAIL": "datyfy@yahoo.com",
    "CONTACT_FAX": "617-569-7367",
    "CONTACT_PHONE": "818-524-1787",
    "CONTACT_STATE": "Iowa",
    "CONTACT_ZIP": 71104,
    "CONTRACTOR": "Colt Norman",
    "CONTRACTOR_ADDRESS": "At dolorem ut inventore id mollitia id minus eveniet molestiae quia porro quod",
    "CONTRACTOR_CITY": "Sequi molestias illum, eum.",
    "CONTRACTOR_EMAIL": "datyfy@yahoo.com",
    "CONTRACTOR_FAX": "617-569-7367",
    "CONTRACTOR_PHONE": "818-524-1787",
    "CONTRACTOR_STATE": "Wisconsin",
    "CONTRACTOR_ZIP": 71104,
    "DESIGNER": "Morgan Mcdowell",
    "DESIGNER_ADDRESS": "At dolorem ut inventore id mollitia id minus eveniet molestiae quia porro quod",
    "DESIGNER_CITY": "Sequi molestias illum, eum.",
    "DESIGNER_EMAIL": "datyfy@yahoo.com",
    "DESIGNER_PHONE": "873-433-7162",
    "DESIGNER_PREPARED_BY": "Colt Norman",
    "DESIGNER_STATE": "Arkansas",
    "DESIGNER_ZIP": 71104,
    "ESTIMATED_COST": null,
    "HABITABLE_SQ_FT": 100,
    "LOT": "Impedit velit duis illum aut necessitatibus vero ullamco proident",
    "OWNER": "Chan Calderon Inc",
    "OWNER_ADDRESS": "Rojas and Smith Inc",
    "OWNER_CITY": "Simpson Sellers Inc",
    "OWNER_EMAIL": "pafi@hotmail.com",
    "OWNER_FAX": null,
    "OWNER_PHONE": 9996669990,
    "OWNER_STATE": "Rhode Island",
    "OWNER_ZIP": 78956,
    "PARCEL_NO": 1221,
    "PERMIT_TYPE": null,
    "PLAT": "Ullam reprehenderit blanditiis in cupiditate tenetur error",
    "PROJECT_NAME": "Jenette Acosta FLOOD",
    "SAGES_ICN": "BLD-2016-000122",
    "STREET_NAME": "100 E Church ST, Xenia Ohio 45385",
    "ZONING_CERTIFICATE_DATE": null,
    "ZONING_CERTIFICATE_NUMBER": null
};